---

AllCops:
  TargetRubyVersion: 2.5

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/AbcSize:
  Max: 20
