#!/usr/bin/env ruby

require_relative '../lib/rake_helpers'

ALL_FILES = Pathname.new(__FILE__).dirname.children.sort

task default: :run

desc 'compile everything'
task :build do
  ALL_FILES.select { |f| f.extname == '.cr' }.each do |src|
    obj = src.sub_ext('')
    next if obj.exist? && obj.mtime > src.mtime
    puts "building #{src.basename}"
    system("crystal build --release #{src}")
  end
end

desc 'run all programs'
task run: :build do
  run_programs(ALL_FILES.select { |f| f.basename.to_s =~ /^\d+$/ })
end
